name: Build Flutter APK

on:
  push:
    branches: ["main"] # অথবা আপনার ব্রাঞ্চের নাম যেমন master হলে master দিন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x" # আপনার ফ্লাটার ভার্সন এখানে দিতে পারেন (যেমন: '3.x.x')
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
