name: Build Watcher APK

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.8"
          channel: stable
          cache: true

      # Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Read version from pubspec.yaml
      - name: Read App Version
        id: version
        shell: bash
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')

          VERSION_NAME=${VERSION%%+*}
          BUILD_NUMBER=${VERSION##*+}

          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      # Build APK
      - name: Build Release APK
        run: flutter build apk --release --verbose

      # Rename APK
      - name: Rename APK
        shell: bash
        run: |
          mkdir -p release

          cp build/app/outputs/flutter-apk/app-release.apk \
          release/Watcher-v${{ steps.version.outputs.version_name }}-build${{ steps.version.outputs.build_number }}.apk

      # Upload APK Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Watcher-v${{ steps.version.outputs.version_name }}-build${{ steps.version.outputs.build_number }}
          path: release/*.apk
